name: Unit Tests
on: workflow_call
jobs:
  unit-tests:
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-22.04-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
        node-version: [ 20.x, 22.x, 24.x ]
        go-version:
          - 1.16.x
    steps:
      - uses: actions/checkout@v4
      - name: 'Install node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
      - name: 'Install Golang ${{ matrix.go-version }}'
        uses: actions/setup-go@v5
        with:
          go-version: '${{ matrix.go-version }}'
      - name: Run Go unit tests
        run: go test ./...
      - name: Install npm dependencies
        run: npm install
      - name: Run JS unit tests
        run: npm test
      - name: Run JS end-to-end tests
        run: npm run end-to-end
